import { Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useRef, useState } from 'react';
import { api } from './api/client';
import Layout from './components/Layout';
import { Box, Button, Container, List, ListItem, TextField, Typography } from '@mui/material';
import { useAuthStore } from './store/auth';
import BpmnModeler from 'bpmn-js/lib/Modeler';

function Login() { const n = useNavigate(); const setToken = useAuthStore(s => s.setToken); const [email, setEmail] = useState('demo'); const [password, setPassword] = useState('demo'); return <Container><Typography variant='h4'>Login</Typography><TextField fullWidth margin='normal' label='Email' value={email} onChange={e=>setEmail(e.target.value)}/><TextField fullWidth margin='normal' label='Password' type='password' value={password} onChange={e=>setPassword(e.target.value)}/><Button variant='contained' onClick={async()=>{const {data}=await api.post('/api/auth/login',{email,password});setToken(data.token);n('/');}}>Login</Button><Button onClick={()=>n('/register')}>Register</Button></Container> }
function Register(){ const n=useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); return <Container><Typography variant='h4'>Register</Typography><TextField fullWidth margin='normal' label='Email' value={email} onChange={e=>setEmail(e.target.value)}/><TextField fullWidth margin='normal' label='Password' type='password' value={password} onChange={e=>setPassword(e.target.value)}/><Button variant='contained' onClick={async()=>{await api.post('/api/auth/register',{email,password});n('/login')}}>Create</Button></Container> }
function Dashboard(){ const [me,setMe]=useState<any>(null); useEffect(()=>{api.get('/api/auth/me').then(r=>setMe(r.data));},[]); return <Typography>Dashboard: {me?.email} ({me?.role})</Typography> }
function Processes(){ const [items,setItems]=useState<any[]>([]); const [name,setName]=useState('New Process'); useEffect(()=>{api.get('/api/processes').then(r=>setItems(r.data));},[]); return <Box><Typography variant='h5'>Processes</Typography><Button onClick={async()=>{await api.post('/api/processes',{key:'proc-'+Date.now(),name,description:'',category:'default'}); const r=await api.get('/api/processes');setItems(r.data);}}>Create</Button><List>{items.map(p=><ListItem key={p.id}><Button href={`/processes/${p.id}`}>{p.name}</Button></ListItem>)}</List></Box> }
function ProcessDetails(){ const {id}=useParams(); const [p,setP]=useState<any>(null); useEffect(()=>{api.get(`/api/processes/${id}`).then(r=>setP(r.data));},[id]); return <Box><Typography variant='h5'>{p?.name}</Typography><Button href={`/processes/${id}/versions`}>Versions</Button></Box> }
function Versions(){ const {id}=useParams(); const [vs,setVs]=useState<any[]>([]); useEffect(()=>{api.get(`/api/processes/${id}/versions`).then(r=>setVs(r.data));},[id]); return <Box><Button onClick={async()=>{await api.post(`/api/processes/${id}/versions`,{bpmnXml:'<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" targetNamespace="Examples"><process id="p" isExecutable="true"><startEvent id="s"/><endEvent id="e"/><sequenceFlow id="f" sourceRef="s" targetRef="e"/></process></definitions>'}); const r=await api.get(`/api/processes/${id}/versions`); setVs(r.data);}}>New version</Button><List>{vs.map(v=><ListItem key={v.id}><Button href={`/processes/${id}/versions/${v.id}/editor`}>v{v.versionNumber} {v.status}</Button><Button onClick={()=>api.post(`/api/processes/${id}/versions/${v.id}/start`,{variables:{assignee:'demo',needLaundry:true}})}>Start</Button></ListItem>)}</List></Box> }
function BpmnEditor(){ const {id,versionId}=useParams(); const ref=useRef<HTMLDivElement>(null); const modelerRef=useRef<any>(null); const [xml,setXml]=useState(''); useEffect(()=>{api.get(`/api/processes/${id}/versions/${versionId}`).then(async r=>{setXml(r.data.bpmnXml); const m=new BpmnModeler({container:ref.current!}); modelerRef.current=m; await m.importXML(r.data.bpmnXml);}); return ()=>modelerRef.current?.destroy();},[id,versionId]); return <Box><Box ref={ref} sx={{height:400,border:'1px solid #ddd'}}/><Button onClick={async()=>{const {xml}=await modelerRef.current.saveXML({format:true}); setXml(xml); await api.put(`/api/processes/${id}/versions/${versionId}/bpmn`,{bpmnXml:xml});}}>Save</Button><Button onClick={async()=>{await api.post(`/api/processes/${id}/versions/${versionId}/publish`)}}>Publish</Button><TextField multiline minRows={8} fullWidth value={xml} onChange={e=>setXml(e.target.value)}/></Box> }
function Instances(){ const [items,setItems]=useState<any[]>([]); useEffect(()=>{api.get('/api/instances').then(r=>setItems(r.data));},[]); return <List>{items.map(i=><ListItem key={i.id}><Button href={`/instances/${i.id}`}>Instance {i.id} {i.status}</Button></ListItem>)}</List> }
function InstanceDetails(){ const {instanceId}=useParams(); const [i,setI]=useState<any>(); const [h,setH]=useState<any[]>([]); useEffect(()=>{api.get(`/api/instances/${instanceId}`).then(r=>setI(r.data)); api.get(`/api/instances/${instanceId}/history`).then(r=>setH(r.data));},[instanceId]); return <Box><Typography>Status: {i?.status}</Typography><Typography>Flowable: {i?.flowableProcessInstanceId}</Typography><List>{h.map((a,idx)=><ListItem key={idx}>{a.activityName} ({a.activityType})</ListItem>)}</List></Box> }
function MyTasks(){ const [tasks,setTasks]=useState<any[]>([]); const [json,setJson]=useState('{"needLaundry":true}'); useEffect(()=>{api.get('/api/tasks/my').then(r=>setTasks(r.data));},[]); return <Box><TextField multiline minRows={4} fullWidth value={json} onChange={e=>setJson(e.target.value)}/><List>{tasks.map(t=><ListItem key={t.id}><Button onClick={async()=>{await api.post(`/api/tasks/${t.id}/complete`,{variables:JSON.parse(json)}); const r=await api.get('/api/tasks/my');setTasks(r.data);}}>Complete {t.name}</Button></ListItem>)}</List></Box> }
function Admin(){ const [p,setP]=useState<any[]>([]); const [i,setI]=useState<any[]>([]); useEffect(()=>{api.get('/api/admin/processes').then(r=>setP(r.data)); api.get('/api/admin/instances').then(r=>setI(r.data));},[]); return <Box><Typography>Processes: {p.length}</Typography><Typography>Instances: {i.length}</Typography></Box> }

function Protected(){ const token=useAuthStore(s=>s.token); return token ? <Layout/> : <Navigate to='/login'/>; }

export default function App(){ return <Routes><Route path='/login' element={<Login/>}/><Route path='/register' element={<Register/>}/><Route element={<Protected/>}><Route path='/' element={<Dashboard/>}/><Route path='/processes' element={<Processes/>}/><Route path='/processes/:id' element={<ProcessDetails/>}/><Route path='/processes/:id/versions' element={<Versions/>}/><Route path='/processes/:id/versions/:versionId/editor' element={<BpmnEditor/>}/><Route path='/instances' element={<Instances/>}/><Route path='/instances/:instanceId' element={<InstanceDetails/>}/><Route path='/tasks' element={<MyTasks/>}/><Route path='/admin' element={<Admin/>}/></Route></Routes> }
